version: "3"

tasks:
  build:
    desc: Do release build
    deps:
      - init
    cmds:
      - cargo build --release --target wasm32-wasi
    sources:
      - "./src/**/*.rs"
      - Cargo.*
    generates:
      - target/wasm32-wasi/release/hello-world-repeater.wasm

  run:
    desc: Run with wasmtime
    deps:
      - build
    cmds:
      - wasmtime --env RUST_LOG=info target/wasm32-wasi/release/hello-world-repeater.wasm

  init:
    desc: Initialize dev environment
    cmds:
      - task: init:target
      - task: init:wasmtime

  init:target:
    cmds:
      - rustup target add wasm32-wasi
    status:
      - rustup target list --installed | grep -q wasm32-wasi

  init:wasmtime:
    cmds:
      - echo "Install wasmtime before continuing"
      - read -p "Press enter to continue:"
    status:
      - command -v wasmtime &>/dev/null
