apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasm-spin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasm-spin
  template:
    metadata:
      labels:
        app: wasm-spin
    spec:
      runtimeClassName: wasmtime-spin
      containers:
        - name: hello-world-repeater
          image: hello-world-repeater:v0.0.1
          command: ["/"]
          env:
            - name: RUST_LOG
              value: info
          resources:
            limits:
              memory: "128M"
              cpu: "1"
